[building]
walls = [
    [0.0, 0.0], 
    [0.0, 47.0], 
    [19.0, 47.0],
    [19.0, 33.0],
    [40.0, 33.0], # 外の長さ未定
    [40.0, 25.5],
    [30.0, 25.5],
    [28.5, 23.5],
    [28.5, 0.0]
]

[[building.room]]
name = "dining"
walls = [
    [0.0, 0.0], 
    [28.5, 0.0], 
    [28.5, 14.6], 
    [21.5, 14.6], 
    [21.5, 15.92],
    [19.0, 15.92],
    [19.0, 9.62], 
    [12.5, 9.62], 
    [12.5, 13.82],
    [8.29, 13.82], 
    [8.29, 9.62], 
    [0.0, 9.62]
]

[[building.room]]
name = "corridor"
walls = [
    [9.79, 13.82], 
    [9.79, 33.0], 
    [14.5, 33.0], 
    [14.5, 31.0],
    [12.5, 31.0],
    [12.5, 13.82]
]

[[building.room]]
name = "entrance"
walls = [
    [12.5, 23.5],
    [12.5, 31.0],
    [14.5, 31.0],
    [14.5, 33.0],
    [24.5, 33.0],
    [24.5, 31.0],
    [28.5, 31.0],
    [28.5, 25.5],
    [24.5, 25.5],
    [24.5, 23.5],
    [21.5, 23.5],
    [21.5, 15.92],
    [19.0, 15.92],
    [19.0, 23.5]
]

[[building.room]]
name = "outside"
walls = [
    [24.5, 33.0],
    [40.0, 33.0],
    [40.0, 25.5],
    [30.0, 25.5],
    [28.5, 23.5],
    [24.5, 23.5],
    [24.5, 25.5],
    [28.5, 25.5],
    [28.5, 31.0],
    [24.5, 31.0],
]

# z座標も必要
[[building.receiver]]
device_id = 1
position = [1.0, 1.0, 0.0]

[[building.receiver]]
device_id = 2
position = [16.0, 1.0, 0.0]
